services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: prismax
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - prismax_postgres_data:/var/lib/postgresql/data

volumes:
  prismax_postgres_data:

